( defclass recommend_fine_reduction ( is-a DERIVED-CLASS ) ( slot defendant ( type ?VARIABLE ) ) )
( defclass recommend_increased_penalty ( is-a DERIVED-CLASS ) ( slot defendant ( type ?VARIABLE ) ) )
( defclass is_high_category_weapon_in_public ( is-a DERIVED-CLASS ) ( slot defendant ( type ?VARIABLE ) ) )
( defclass to_pay_less ( is-a DERIVED-CLASS ) ( slot value ( type INTEGER ) ) )
( defclass to_increase_penalty ( is-a DERIVED-CLASS ) ( slot value ( type INTEGER ) ) )
( defclass to_pay_max ( is-a DERIVED-CLASS ) ( slot value ( type INTEGER ) ) )
( defclass to_pay_min ( is-a DERIVED-CLASS ) ( slot value ( type INTEGER ) ) )
